resource_group_name = "Geicoautomationscript"
location            = "East US"
app_service_plan_name = "stag-plan"
web_app_name        = "stag-web-app"
sku_size            = "B1"
os_type             = "Windows"
